lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0

