title: Tesis de grado
description: Mi proyecto de tesis para obtener el grado de ingeniero mecánico en la Universidad Nacional de San Agustín de Arequipa - 2023.
lsi: false
safe: true
source: .
incremental: false
highlighter: kramdown
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0

